### ISSUE TITLE
Handle invalid Environment Key

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith-go-client#6]
Currently the SDK fails silently if passed an invalid `environment key`. We should handle this better by providing feedback to the developer that the API key was not found.

**Comment by craigpastro** [comment]
👋 I suppose this issue is no longer relevant as `NewClient` now takes an `apiKey` as its first argument. Or did I misunderstand the issue? Thanks!

**Comment by gagantrivedi** [comment]
Hi @craigpastro ! The issue is still relevant. We have two types of environment keys, server side (can be used by server side SDK's to run in local evaluation mode e.g) and client side. This issue is about adding a check to make sure if the user has enabled local evaluation mode, the key they are using is `server side`(i.e: they start with `ser`). You can have a look at the python implementation to see a working example of this: https://github.com/Flagsmith/flagsmith-python-client/blob/main/flagsmith/flagsmith.py#L122C59-L122C59

**Comment by craigpastro** [comment]
Hi @gagantrivedi! Ah, that's an easy fix I think. I'll create a PR.
